; Ping Status - Devices
; Author: Fenyvesi István from Kineneta Studio
; Version: 2.0
; License: Creative Commons BY-NC-SA 3.0

[Variables]
DeviceCount=3

Device1_Name=Kineneta
Device1_IP=kineneta.com

Device2_Name=DeviantArt
Device2_IP=deviantart.com

; Add more devices by copying the pattern above and incrementing DeviceCount


Device3_Name=Random IP
Device3_IP=192.168.5.15

PingTimeout=1000
UpdateInterval=5
